---
title: "Expected Generations for Lineages to Encounter T% of the Test Case Set with down sampling"
output: 
  html_document: 
    keep_md: true
    toc: true
    toc_float: true
    collapsed: false
    theme: default
  pdf_document: default
---

```{r}
library(plyr)
library(dplyr)
library(ggplot2)
library(cowplot)
```

This assumes that _all_ cohorts are equally sized.

```{r}
# Expected number of generations for a lineage to encounter a given threshold (e.g., 1/2 or 1/3, etc) of test cases at a given number of (equally sized) cohorts.
# - This function must be vectorize-able, so it can't be as clean to read as I'd like.
expected_gens <- function(threshold, num_cohorts) {
  return ( ifelse( (num_cohorts == 1 | threshold <= (1.0/num_cohorts)), 1, log2(1-threshold) / ( log2(num_cohorts - 1) - log2(num_cohorts) ) ) )
  # if (threshold > 1.0) {
  #   return(Inf)
  # } else if ( num_cohorts == 1 | threshold <= (1.0/num_cohorts) ) { 
  #   return(1)
  # } else {
  #   print(log2(1-threshold) / ( log2(num_cohorts - 1) - log2(num_cohorts) ))
  #   return(  )  
  # }
}

```

Plot!

```{r}

cohort_configs <- c(1, 2, 4, 8, 16, 32, 64, 128, 256)

# c("2 cohorts", "4 cohorts", "8 cohorts", "16 cohorts", "32 cohorts", "64 cohorts", "128 cohorts", "256 cohorts")

ggplot(data=data.frame(x=c(0.0, 1.0)), mapping=aes(x=x)) +
  stat_function(fun=expected_gens, n=1000, args=list(num_cohorts = 2), aes(colour="50% training")) +
  stat_function(fun=expected_gens, n=1000, args=list(num_cohorts = 4), aes(colour="25% training")) +
  stat_function(fun=expected_gens, n=1000, args=list(num_cohorts = 10), aes(colour="10% training")) +
  stat_function(fun=expected_gens, n=1000, args=list(num_cohorts = 20), aes(colour="5% training")) +
  ylab("Expected Generations") + xlab("Proportion of tests encountered by a lineage") +
  xlim(0.0, 1.0) + ylim(0, 100) +
  scale_color_discrete("Downsample Rate", limits= c("50% training", "25% training", "10% training", "5% training")) + 
  coord_flip() +
  ggsave("expected_generations.png", height=5,width=7,dpi=600)

```
